### ISSUE TITLE
[Feature Request] Support "zmbkpose -r" to restore all accounts

### ISSUE THREAD

**Issue by xiebopublic** [bggo/Zmbkpose#13]
Currently I can use "zmbkpose -f" to backup all accounts without specifying the account name one by one, but I have to specify the account name one by one (e.g., zmbkpose -r myname1@company.com,myname2@company.com session_name) in order to restore them.

I request a new feature to support "zmbkpose -r" to restore all accounts without specifying the account name one by one.

**Comment by bggo** [comment]
Hello xiebopublic, I believe this will be in the next version by the end of year. Thanks to help us to improve zmbkpose.

[]`s

**Comment by wfelipew** [comment]
This feature has been implemented on this new version (2.0),
See the option: --restoreAllAccounts
