### ISSUE TITLE
I would like to collaborate

### ISSUE THREAD

**Issue by liandros** [bggo/Zmbkpose#16]
I made ​​some modifications, and I would like to collaborate with the proyect.  How I can to continue?

**Comment by bggo** [comment]
... =D.

Whats your user on github?

On Thu, May 17, 2012 at 3:10 PM, liandros <
reply@reply.github.com

> wrote:
> 
> I made some modifications, and I would like to collaborate with the
> proyect.  How I can to continue?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bggo/Zmbkpose/issues/16

## 
- -
  Bruno Gurgel Gomes de Oliveira (@bggo)
  IBTA | LPIC - I | LPIC - II | RHCSA | RHCE | ITILv3 | Scrum Master
  Consutor FOSS na 4Linux | Free Software Consultant
  http:// http://noroyalties.orgwww.brunogurgel.com.br | bruno@linux.com

**Comment by liandros** [comment]
my github user is liandros
