### ISSUE TITLE
zmbkpose rewrite proposal

### ISSUE THREAD

**Issue by liandros** [bggo/Zmbkpose#19]
This is a complete rewrite proposal to zmbkpose.
I present this to the team members for feedback before attempting to upload.
        \* Full rewrite of source code 
        \* New storage format for backups, incomppatible with older versions
        \* More flexibility, simplicity backup storage, and performance
        \* Conditional incremental or full backup(how old is the last backup)
        \* List information about backups 
        \* Restore the account to a specific time

What do you think?
The code is in https://docs.google.com/open?id=0B9IDNSyRLvcBdVN4cWd6U2ZQUWc

**Comment by bggo** [comment]
Nice! ...

I have no words to describe how happy I am! Proposal accepted!!!!
Wellcome to the team! =D

What do you thing in push this new version to git hub!?

You need to include your name and e-mail on the GPL header. =D

Nice work! I've been reading about 3 mails by week since I put it on
github. Thanks a lot!!! =D

[]'s

On Thu, Jul 12, 2012 at 12:56 PM, liandros <
reply@reply.github.com

> wrote:
> 
> This is a complete rewrite proposal to zmbkpose.
> I present this to the team members for feedback before attempting to
> upload.
>         \* Full rewrite of source code
>         \* New storage format for backups, incomppatible with older versions
>         \* More flexibility, simplicity backup storage, and performance
>         \* Conditional incremental or full backup(how old is the last
> backup)
>         \* List information about backups
>         \* Restore the account to a specific time
> 
> What do you think?
> The code is in
> https://docs.google.com/open?id=0B9IDNSyRLvcBdVN4cWd6U2ZQUWc
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bggo/Zmbkpose/issues/19

## 
- -
  Bruno Gurgel Gomes de Oliveira (@bggo)
  IBTA | LPIC - I | LPIC - II | RHCSA | RHCE | ITILv3 | Scrum Master
  Analista de Sistemas no R7.com | System Administrator at R7.com
  http://www.brunogurgel.com.br/about | bruno@linux.com

**Comment by liandros** [comment]
Thanks Bruno for allowing me to participate
I'll wait for the commit to github.
    1) I think I should consulting before replacing the work of other guys.
    2) The experiences of others can help me in finding bugs.
Again, thank you.

2012/7/12 Bruno Gurgel
reply@reply.github.com:

**Comment by bggo** [comment]
Liandros,

The team since the project starts has gone.
- Rubens how write the first version, and allow me to continue and upload
  to git hub don't have any intention to continue;
- Alan, just write some code, but never show him self again;

....  We, just need to ask Willian that had some planls to this. But, plans
I saw just a commit in a year. Let me copy him.

[]'s

On Thu, Jul 12, 2012 at 3:06 PM, liandros <
reply@reply.github.com

> wrote:
> 
> Thanks Bruno for allowing me to participate
> I'll wait for the commit to github.
>     1) I think I should consulting before replacing the work of other guys.
>     2) The experiences of others can help me in finding bugs.
> Again, thank you.
> 
> 2012/7/12 Bruno Gurgel
> reply@reply.github.com:
> 
> > Nice! ...
> > 
> > I have no words to describe how happy I am! Proposal accepted!!!!
> > Wellcome to the team! =D
> > 
> > What do you thing in push this new version to git hub!?
> > 
> > You need to include your name and e-mail on the GPL header. =D
> > 
> > Nice work! I've been reading about 3 mails by week since I put it on
> > github. Thanks a lot!!! =D
> > 
> > []'s
> > 
> > On Thu, Jul 12, 2012 at 12:56 PM, liandros <
> > reply@reply.github.com
> > 
> > > wrote:
> > > 
> > > This is a complete rewrite proposal to zmbkpose.
> > > I present this to the team members for feedback before attempting to
> > > upload.
> > >         \* Full rewrite of source code
> > >         \* New storage format for backups, incomppatible with older
> > > versions
> > >         \* More flexibility, simplicity backup storage, and performance
> > >         \* Conditional incremental or full backup(how old is the last
> > > backup)
> > >         \* List information about backups
> > >         \* Restore the account to a specific time
> > > 
> > > What do you think?
> > > The code is in
> > > https://docs.google.com/open?id=0B9IDNSyRLvcBdVN4cWd6U2ZQUWc
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/bggo/Zmbkpose/issues/19
> > 
> > ## 
> > - -
> >   Bruno Gurgel Gomes de Oliveira (@bggo)
> >   IBTA | LPIC - I | LPIC - II | RHCSA | RHCE | ITILv3 | Scrum Master
> >   Analista de Sistemas no R7.com | System Administrator at R7.com
> >   http://www.brunogurgel.com.br/about | bruno@linux.com
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/bggo/Zmbkpose/issues/19#issuecomment-6941107
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bggo/Zmbkpose/issues/19#issuecomment-6942854

## 
- -
  Bruno Gurgel Gomes de Oliveira (@bggo)
  IBTA | LPIC - I | LPIC - II | RHCSA | RHCE | ITILv3 | Scrum Master
  Analista de Sistemas no R7.com | System Administrator at R7.com
  http://www.brunogurgel.com.br/about | bruno@linux.com

**Comment by bggo** [comment]
Like u saw, Filipe did not answer. =(

I recieved another ask for help today, but I can't help coz' I don't have more may environnmet to do that. =(
Have a look:

Hola antes de todo gracias por este scrip que ayuda bastante a gente como yo

Tengo el siguiente problema cuando quiero restaurar el full backup me sale este error por cuenta

<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /service/home/virus-quarantine.vdl9csoer@asteriskperu.org/Trash. Reason:
<pre>    system failure: tgz formatter failure</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/>

Quisiera saber si estoy haciendo algo mal al tratar de recuperar un backup gracias
Reply to this email directly or view it on GitHub:
https://github.com/bggo/Zmbkpose/issues/20

=D So, maybe now it's a goot time to upgrade, and if you can help him.... =/

Kind Regarsd

**Comment by diegolima** [comment]
Hi! I've downloaded the code and I'll put it through some testing. I suggest we start a new branch and develop this script on it - in the meantime we can continue to maintain the current code on our master branch.

If the rewritten script proves to be better, reliable and easier to maintain we can then phase out our current master branch.

**Comment by liandros** [comment]
2012/7/25 Diego Alencar Alves de Lima
reply@reply.github.com:

> Hi! I've downloaded the code and I'll put it through some testing. I suggest we start a new branch and develop this script on it - in the meantime we can continue to maintain the current code on our master branch.
> 
> If the rewritten script proves to be better, reliable and easier to maintain we can then phase out our current master branch.

totally agree.
I am a novice in git, if someone has the knowledge to build the
branch, please do so. At the moment I am reading about git.

**Comment by liandros** [comment]
Rewrite proposal pushed as a new branch "rewrite_proposal_v2.0"
