### ISSUE TITLE
zmbkpose backups apparently only Inbox Sent Trash and Junk folders

### ISSUE THREAD

**Issue by sctt** [bggo/Zmbkpose#29]
Hello,

i have never used zmbkpose but i took a look at the src code cause i needed some tips for my scripts.

i noticed that yours queries to the zimbra mailbox are those three:

https://$MAILHOST:7071/home/$MAIL/?fmt=tgz
https://$MAILHOST:7071/home/$MAIL/Junk?fmt=tgz
https://$MAILHOST:7071/home/$MAIL/Trash?fmt=tgz

the first one export only Sent and Inbox, the last two Junk and Trash.
so what about Drafts folder? and every custom folder which could be created?

that can be solved with only one query query instead of four or one for each custom folder, here it is:

https://$MAILHOST:7071/home/$MAIL/Trash?fmt=tgz%20is:anywhere

hope that helped.

**Comment by liandros** [comment]
2013/2/5 sctt notifications@github.com
