### ISSUE TITLE
halts on curl error

### ISSUE THREAD

**Issue by maxxer** [bggo/Zmbkpose#32]
even if launched with -u switch, the backup is halted on curl error. I got this result :+1: curl: (23) Failed writing body
and the backup stopped...
Using proposed rewrite branch

**Comment by liandros** [comment]
2013/2/25 Lorenzo Milesi notifications@github.com

**Comment by maxxer** [comment]
I'm experiencing problems with my NFS share. Anyway, the backup should go further for the next account

**Comment by liandros** [comment]
2013/3/6 Lorenzo Milesi notifications@github.com
