### ISSUE TITLE
restoring issues in zimbra8

### ISSUE THREAD

**Issue by ghost** [bggo/Zmbkpose#38]
when iam migrating my server from zimbra7 to zimbra8,im facing problems in restoration.if im restoring the full backup for 3 times,my mailbox size also increased by 3 times(if it is 10MB after restoration for 3 times it is 30MB).can any one suggest what are the changes in zmbkpose file or any zimbra8 compatable zmbkpose?

**Comment by liandros** [comment]
Yes. Me to, I can confirm this problem migrating from 5.0.16 to 8.0.3.
It is a zimbra bug, not a zmbkpose bug. Please, from your mailbox account in zimbra 7, go to preference, and use the  mailbox export utility. Then, in zimbra8, from your mailbox, import the backup file two times. Important: note the "Solve problem of duplicates" option, and use "ignore".
Check your mailbox for duplicates. If you have duplicate mails, then give me your exact zimbra version (source and target of migration) using (with zimbra user) the command:
  zmcontrol -v
There is no a bug if you export and import on same zimbra version, but apparently,  it is not working through zimbra versions.
I going to post a request in zimbra forums with our information.

**Comment by liandros** [comment]
Confirmed problem migrating from zimbra 5.0.16 to 8.0.3 
Confirmed problem migrating from zimbra 7 to 8 
It is a zimbra bug, not a zmbkpose bug.
