### ISSUE TITLE
Backup zmbkpose Permission Denied

### ISSUE THREAD

**Issue by rafeltrps** [bggo/Zmbkpose#39]
Quando executo o comando para efetuar o backup ele começa a efetuar o backup, no entanto após alguns minutos lendo a mailbox ele me apresenta o seguinte erro:

postdrop: warning: mail_queue_enter: create file maildrop/39119.13181: Permission denied
postdrop: warning: mail_queue_enter: create file maildrop/39378.13181: Permission denied
postdrop: warning: mail_queue_enter: create file maildrop/39625.13181: Permission denied
postdrop: warning: mail_queue_enter: create file maildrop/40184.13181: Permission denied
postdrop: warning: mail_queue_enter: create file maildrop/40411.13181: Permission denied
postdrop: warning: mail_queue_enter: create file maildrop/40642.13181: Permission denied
postdrop: warning: mail_queue_enter: create file maildrop/40851.13181: Permission denied

E vai crescendo. Alguém pode me ajudar?

**Comment by liandros** [comment]
Helo, I think it is no a zmbkpose error. Searching in zimbra site, I find
the follow:
exec in the zimbra server as root user :
   /opt/zimbra/libexec/zmfixperms --verbose

then restart zimbra, as zimbra user  exec:
  zmcontrol stop
  zmcontrol start

2013/7/1 rafeltrps notifications@github.com
