### ISSUE TITLE
Add option to split FULL backups in burnable size

### ISSUE THREAD

**Issue by maxxer** [bggo/Zmbkpose#41]
An user may wish to backup their emails on DVD. Actually the script can produce very big TARs, having an option to split them up in 4.4G automatically can be a good thing.

**Comment by liandros** [comment]
I suposse you are using zmbkpose rewrite_proposal_v2.0 branch . 

I think zmbkpose should not do this job. zmbkpose is aimed at the administrator, not the end user, so a dvd backup in the hands of the end user, not very useful, he can not restore it.
Now in the hands of admin, chunking the backup file is easy with tools like "split", but if this makes zmbkpose then becomes complex restore from a backup divided, as it is now necessary to corroborate the correct sequence.

What do you think?

On the other hand, it seems elegant zmbkpose can generate backup to stdout, so it can be sent by pipe to a command such as "split".

I made the following change:
In recent last commit "backup output file (--bf) now support - as file name for stdout" (622c50a79f), you can use - for backup to stdout and then pipe to splitter command.

Then, you can use : 4500000000 ~= 4.2GB 
  zmbkpose -i -a account --bf - |  split --bytes=4500000000   -d --verbose - account_dvd_full_backup.
