### ISSUE TITLE
Out of memory issue

### ISSUE THREAD

**Issue by mjo09a** [bggo/Zmbkpose#43]
When I try to run zmbkpose -f I keep getting a "DNS SRV: out of memory?" error and i cannot proceed with the backup.  Is there any reason I would be getting this? I have 4GB of RAM so I wouldn't think that would be the issue.

**Comment by gregor2005** [comment]
hi, i have the same problem here.
why is this issue closed? what was the solution?

king regards
gregor

**Comment by gregor2005** [comment]
i found the solution during debugging the script
my problem was that i haven't saved a ldap servername in the config, value LDAPMASTERSERVER

king regards
gregor

**Comment by liandros** [comment]
ok. Sorry for the delay.

2013/10/3 gregor2005 notifications@github.com
