### ISSUE TITLE
Fix possible typo in  https://github.com/bggo/Zmbkpose/blob/issue35/src/zmbkpose

### ISSUE THREAD

**Issue by neotheonce** [bggo/Zmbkpose#45]
There is a typo at line 319 in file issue35/src/zmbkpose
-   "https://$mailhost:7071/homei/$mailbox/?fmt=tgz$search_query" ;then
-   "https://$mailhost:7071/home/$mailbox/?fmt=tgz$search_query" ;then

**Comment by liandros** [comment]
Yes...  you're right. Testing code remained there.
thank you very much.
