### ISSUE TITLE
ERROR:You don't have "gawk" command, or it is not in your PATH

### ISSUE THREAD

**Issue by arekstuka** [bggo/Zmbkpose#47]
Hi, 

I just setup new install ubuntu server ver 12.04 , then install zimbra, everything is working good. sending / receiving email. now i want to install zmbkpose backup (i did this already 12 months ago on ubuntu 10, i use this same instruction and backup working OK.)
Now with ubuntu 12.04 ,im go thru readme file from revrite proposal.i think :) all files in on right places 
but when i try to run backup manually i have error: ERROR:You don't have "gawk" command, or it is not in your PATH, 

what can be wrong?

**Comment by arekstuka** [comment]
just find the problem in code  :[ -z "$AWK_cmd" ] && AWK_cmd=$(which gawk) || { no_command_error gawk; exit 1 ;}

should be: 
[ -z "$AWK_cmd" ] && AWK_cmd=$(which awk) || { no_command_error awk; exit 1 ;}

i will test it tomorrow full backup and incremental and than post here results

**Comment by arekstuka** [comment]
everything is working good,

**Comment by liandros** [comment]
Thanks Arek for this suggest. This has generated the commit 20126ff (
https://github.com/bggo/Zmbkpose/commit/20126ffdb81c1cc57a266e6ccd22d6fece0ce6db
)

2014-02-16 17:54 GMT-03:00 Arek notifications@github.com:
