### ISSUE TITLE
Disaster Recovery Support

### ISSUE THREAD

**Issue by asmartin** [bggo/Zmbkpose#66]
This looks like a great tool for Zimbra Open Source edition, however I am curious as to why it is stated that it does not support DR. If you have a copy of backups from a live Zimbra server created with zmbkpose, why couldn't you use it to restore those backups to have a fully-functioning copy of the server on new hardware?

**Comment by ancientz** [comment]
I would say that DR is a little more complex than just returning the user data. On a disaster with your cluster, you would loose all configuration, and if you have a multi-server cluster, thats is going to take a while to rebuild, and only after you rebuild the cluster you would restore the backup. So what I mean is, you can return the user data, but not the whole cluster, only the data and configuration of the user, that is not a disaster recover but actually only data backup.

**Comment by asmartin** [comment]
Thanks for the clarification. So if I have a second server where I've also
installed Zimbra and made the same system tweaks (e.g. /etc/sysctl.conf),
then zmbkpose would be able to completely restore all data (including
things like CoS configuration, Zimbra postfix settings, etc)?

**Comment by ancientz** [comment]
No, as I understand, zmbkpose only backups the user configuration and data, that is, he's preferences on zimbra and the actual mail, calendar and contacts, not anything else. That's why Its not considered a DR tool.

**Comment by asmartin** [comment]
Thanks for the clarification
